services:
  chzzk-auto-recoder:
    build: .
    restart: unless-stopped
    user: '${UID:-1000}:${GID:-1000}'
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./recordings:/app/recordings
    environment:
      - TZ=Asia/Seoul

    logging:
      options:
        max-size: '10m'
        max-file: '3'
