services:
  chzzk-auto-recorder:
    container_name: chzzk-auto-recorder
    build: .
    restart: unless-stopped
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./recordings:/app/recordings
    environment:
      - TZ=Asia/Seoul

    logging:
      options:
        max-size: '10m'
        max-file: '3'
